name: Build & Release
on:
  push:
    branches:
      - master
      - testing

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for .vercel config
        id: check_vercel_config
        uses: andstor/file-existence-action@v1
        with:
          files: ".vercel/project.json"

      - name: Setup .npmrc for build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      # Build
      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

      # Deploy
      - name: Deploy on Vercel (testing)
        uses: amondnet/vercel-action@v20
        if: steps.check_vercel_config.outputs.files_exists == 'true' && endsWith(github.ref, '/testing')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false

      - name: Deploy on Vercel (production)
        uses: amondnet/vercel-action@v20
        if: steps.check_vercel_config.outputs.files_exists == 'true' && endsWith(github.ref, '/master')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-args: "--prod"
          alias-domains: |
            react-test.paolotremadio.com
